services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'YourPassword@123'
    ports:
      - '1433:1433'
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata: